baseURL = 'https://jakobvendegna.dev/'
languageCode = 'en-us'
title = "Jakob Vendegna"
theme = 'ananke'

sectionPagesMenu = "main"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 30
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 40