# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Format
        run: npm run format
        
      - name: Build app
        run: npm run build
        
      - name: Cloud Storage Uploader
        # You may pin to the exact commit or the version.
        # uses: google-github-actions/upload-cloud-storage@c43ab88dab05a52b87417245e108fa54204a652f
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          # Optional service account key to use for authentication to GCS. This should be the JSON
          # formatted private key which can be exported from the Cloud Console. The
          # value can be raw or base64-encoded.
          credentials: ${{ secrets.GCS_STORAGE_CRED }}
          # The path to a file or folder inside the action's filesystem
          # that should be uploaded to the bucket.
          # You can specify either the absolute path or the relative path from the action.
          path: public/
          # GCS bucket name of form <bucketname> or with an optional prefix
          #of form <bucketname>/<prefix>
          destination: jakobvendegna-dev
        
      
